version: '3.8'

services:
  nurse-scrapper:
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start:dev"]
